# Generated by Django 4.1.7 on 2023-10-25 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(default=1)),
                ('image', models.ImageField(default='default.jpg', upload_to='produce_pics')),
                ('description', models.TextField(max_length=800)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=40)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(default=1)),
                ('image', models.ImageField(default='default.jpg', upload_to='trade_pics')),
                ('description', models.TextField(max_length=800)),
                ('ros_min', models.FloatField()),
                ('ros_max', models.FloatField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=40)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('payback_date', models.DateField(blank=True, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=300, null=True)),
                ('partners', models.ManyToManyField(to='Asset.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(default='default.jpg', upload_to='farmCrop_pics')),
                ('price', models.FloatField()),
                ('ros_min', models.FloatField()),
                ('ros_max', models.FloatField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=800)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('payback_date', models.DateField(blank=True, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=300, null=True)),
                ('partners', models.ManyToManyField(to='Asset.partner')),
            ],
        ),
    ]
