# Generated by Django 4.1.7 on 2023-10-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='payout',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='payout',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
