# Generated by Django 4.1.7 on 2023-10-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset', '0002_farm_payout_trade_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='payout',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='payout',
            field=models.FloatField(blank=True),
        ),
    ]
