# Generated by Django 4.1.7 on 2023-10-25 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('bio', models.TextField(max_length=3000)),
                ('image', models.ImageField(default='image.jpg', upload_to='team_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('bio', models.TextField(max_length=3000)),
                ('image', models.ImageField(default='image.jpg', upload_to='team_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(default='default.jpg', upload_to='message_tags')),
                ('content', models.CharField(max_length=3000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(default='AgrivestAfrica', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('bio', models.TextField(max_length=3000)),
                ('image', models.ImageField(default='image.jpg', upload_to='team_pics')),
            ],
        ),
    ]
